server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 10.0.250.106:8848 #配置Nacos 的IP地址

management:
  endpoint:
    web:
      exposure:
        include: '*'