server:
  port: 8084

spring:
  application:
    name: nacos-order-provider
  cloud:
    nacos:
      discovery:
        server-addr: 10.0.250.106:8848 #配置Nacos 的IP地址
    sentinel:
      transport:
        #配置Sentinel dashboard地址
        dashboard: 192.168.20.19:8080
        #默认8719端口，加入被占用则会自动从8719开始依次+1扫描，直到找到未被占用的端口
        port: 8719

# 消费者将要去访问微服务名称（注册成功进nacos的服务提供者）
service-url:
  nacos-user-service: http://nacos-payment-provider